name: "Build and Deploy"

on:
  push:
    branches:
      - main
    paths-ignore:
      - .gitignore
      - README.md

permissions:
      id-token: write
      contents: read

env:
  AZURE_WEBAPP_NAME: app-iot-dev
  AZURE_WEBAPP_PACKAGE_PATH: 'my-app-path'
  NODE_VERSION: '24.12'
